REPORT zprog_diff.

CLASS zcl_test_diff DEFINITION.
  PUBLIC SECTION.
    METHODS test_1
      IMPORTING
        iv_test TYPE i.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_test_diff IMPLEMENTATION.
  METHOD test_1.
  ENDMETHOD.
ENDCLASS.
